[workspace]
resolver = "2"

members = [
    "crates/app",
    "crates/ht/interface",
    "crates/space",
    "crates/spatializer",
]

exclude = [
    "crates/ht/platform/core-motion"
]

[workspace.dependencies]
nalgebra = "0.32.5"
