[package]
name = "irt-ht-api"
version = "0.1.0"
edition = "2021"

[dependencies]
irt-ht-interface = { path = "../../../libs/ht" }
tracing = "0.1.40"

[target.'cfg(target_os = "macos")'.dependencies]
irt-ht-core-motion = { path = "../core-motion" }
