[package]
name = "irt-ht-core-motion"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"]

[build-dependencies]
swift-bridge-build = "0.1.55"

[dependencies]
swift-bridge = "0.1.55"
irt-ht-interface = { path = "../../interface" }
